# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('title', 'source')]),
        ),
    ]
